import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 需要按照版本区分的文档
  mainSidebar: [
    {
      type: 'autogenerated',
      dirName: 'docs',
    },
  ],
  quickSidebar: [
    {
      type: 'autogenerated',
      dirName: 'quick',
    },
  ],

  // 如下内容不需要区分版本的
  releaseSidebar: [
    {
      type: 'autogenerated',
      dirName: 'release',
    },
  ],
  examplesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'examples',
    },
  ],
  communitySidebar: [
    {
      type: 'autogenerated',
      dirName: 'community',
    },
  ],
  // 教程导航
  courseSidebar: [
    'course/社区教程',
    'course/视频入门教程',
    'course/starbook/starbook',
    'course/proxima-book/proxima-book',
  ],
  courseStarBookSidebar: [
    {
      type: 'autogenerated',
      dirName: 'course/starbook',
    },
  ],
  courseProximaBookSidebar: [
    {
      type: 'autogenerated',
      dirName: 'course/proxima-book',
    },
  ],
};

export default sidebars;
